---
- name: 'Install jdk'
  apt:
    name: [
      'ca-certificates-java',
      'openjdk-8-jre',
      'openjdk-8-jdk'
    ]
    state: latest

- name: 'Set JAVA_HOME'
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-armhf/'