---
- name: 'Set hostname facts'
  set_fact:
    full_hostname: "{{ inventory_hostname }}"
    short_hostname: "{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/piot.git
    dest: piot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

- name: 'create kvs supervisord confs'
  become: yes
  template:
    src: kvs_sub.conf.j2
    dest: /etc/supervisor/conf.d/kvs_sub.conf
    mode: 0644

- name: 'login into aws docker registry'
  shell: $(aws ecr get-login --region us-east-1 --no-include-email)

- name: 'pull kvs docker image'
  docker_image:
    name: "{{ vstream_docker_image }}"

- name: 'restart kvs_sub via supervisor'
  supervisorctl:
    name: kvs_sub
    state: restarted
  become: yes