---
- name: 'Ensures pi user aws dir exists'
  file:
    path: "{{ user_dir }}/.aws"
    state: directory
    mode: 0700
    owner: "{{ user }}"
    group: "{{ group }}"

- name: 'Ensures root user aws dir exists'
  file:
    path: "/root/.aws"
    state: directory
    mode: 0700
    owner: root
    group: root

- name: 'Amazon config for pi'
  template:
    src: aws_config.j2
    dest: "{{ user_dir }}/.aws/config"
    mode: 0600
    owner: "{{ user }}"
    group: "{{ group }}"

- name: 'Amazon config for root'
  template:
    src: aws_config.j2
    dest: /root/.aws/config
    mode: 0600
    owner: root
    group: root
