---
- name: 'Set hostname facts'
  set_fact:
    full_hostname="{{ inventory_hostname }}"
    short_hostname="{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Clone/Update latest repo'
  git: repo={{ github_repo }}
      dest={{ webapps_dir }}
      accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: 'create relay supervisord confs'
  become: yes
  template: src=relay_sub.conf.j2 dest=/etc/supervisor/conf.d/relay_sub-{{ item.value.pin }}.conf mode=0644
  with_dict: "{{ relays }}"

- name: 'Restart relay via supervisor'
  supervisorctl: name=relay_sub-{{ item.value.pin }} state=restarted
  become: yes
  with_dict: "{{ relays }}"
