---
- name: 'Set hostname facts'
  set_fact:
    full_hostname: "{{ inventory_hostname }}"
    short_hostname: "{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/piot.git
    dest: piot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

- name: 'Download kvs producer files (pi zero)'
  become: yes
  get_url:
    url: http://shared.snerted.com/kvs-producer-armv6l.tgz
    dest: /opt/kvs-producer.tgz
    mode: 0444
  when: ansible_machine == "armv6l"

- name: 'Download kvs producer files (pi)'
  become: yes
  get_url:
    url: http://shared.snerted.com/kvs-producer-armv7l.tgz
    dest: /opt/kvs-producer.tgz
    mode: 0444
  when: ansible_machine == "armv7l"

- name: 'Extract kvs producer files'
  become: yes
  unarchive:
    src: /opt/kvs-producer.tgz
    dest: /opt
    remote_src: yes

- name: 'Set kvs producer log level to WARN'
  template:
    src: kvs_log_configuration.j2
    dest: /opt/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-native-build/kvs_log_configuration
    owner: root
    group: root
    mode: 0644

- name: 'create kvs_producer supervisor conf'
  become: yes
  template:
    src: kvs_producer.conf.j2
    dest: /etc/supervisor/conf.d/kvs_producer.conf
    mode: 0644

- name: 'restart kvs_producer via supervisor'
  supervisorctl:
    name: kvs_producer
    state: present
  become: yes