---
- name: 'Set hostname facts'
  set_fact:
    full_hostname: "{{ inventory_hostname }}"
    short_hostname: "{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Install python dependencies'
  pip:
    name: [
      'picamera'
    ]
    state: latest
  become: yes

- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/piot.git
    dest: piot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

#- name: 'create timelapse supervisor conf'
#  become: yes
#  template:
#    src: timelapse.conf.j2
#    dest: /etc/supervisor/conf.d/timelapse.conf
#    mode: 0644
#
#- name: 'restart timelapse via supervisor'
#  supervisorctl:
#    name: timelapse
#    state: present
#  become: yes
-
- name: 'Crontab entry snapshot once a minute'
  cron:
    name: "snapshot every minute"
    minute: "0"
    job: "/home/pi/piot/snapshot.py --width 1024 --height 768 --nix_before 8 --nix_after 17"
  become: yes
  become_user: "{{ user }}"

- name: 'Crontab entry for timelapse hourly'
  cron:
    name: "timelapse hourly archive"
    minute: "0"
    job: "/usr/local/bin/aws s3 mv /tmp s3://archive.snerted.com/ --recursive --exclude \"*\" --include \"timelapse-{{ short_hostname }}*.jpg\""
  become: yes
  become_user: "{{ user }}"

