---
- name: 'Set hostname facts'
  set_fact:
    full_hostname: "{{ inventory_hostname }}"
    short_hostname: "{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Install python dependencies'
  pip:
    name: [
      'boto3'
    ]

- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/piot.git
    dest: piot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

- name: 'Crontab entry for pi metrics'
  cron:
    name: "pi metrics"
    minute: "*/5"
    job: "/home/pi/piot/perf_cw.py -n {{ iot_namespace }} --hostname {{ short_hostname }}"
  become: yes
  become_user: "{{ user }}"

- name: 'Crontab entry for host info once a day'
  cron:
    name: "host info daily"
    hour: "23"
    minute: "0"
    job: "/home/pi/piot/host_info.py -e {{ aws_iot_endpoint }} -r {{ creds_location }}/AmazonRootCA1.pem -c {{ creds_location }}/{{ iot_cert }}-certificate.pem.crt -k {{ creds_location }}/{{ iot_cert }}-private.pem.key"
  become: yes
  become_user: "{{ user }}"

- name: 'Set rc.local to execute host_info at boot'
  lineinfile:
    path: /etc/rc.local
    regexp: '^/home/pi/piot/host_info.py'
    line: '/home/pi/piot/host_info.py -e {{ aws_iot_endpoint }} -r {{ creds_location }}/AmazonRootCA1.pem -c {{ creds_location }}/{{ iot_cert }}-certificate.pem.crt -k {{ creds_location }}/{{ iot_cert }}-private.pem.key'
    owner: root
    group: root
    mode: 0755
    insertbefore: 'exit 0'