---
- name: 'Install dependent packages'
  apt:
    name: [
      'apt-transport-https',
      'ca-certificates',
      'software-properties-common'
    ]

- name: 'Install docker from get.docker.com'
  shell: "curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh"

- name: 'Adding pi to docker group'
  become: yes
  user: name='{{ user }}'
    groups=docker
    append=yes

- name: 'Install python dependencies'
  pip:
    name: [
      'docker'
    ]
    state: latest
